# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8081/login1
Content-Type: application/x-www-form-urlencoded;

login=3&password=3
###

###
GET http://localhost:8082/api/account/get-secure
Authorization: Barer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzIiwiZXhwIjoxNTQ5NjcyNTcyfQ.3ZTUxE5aXddRl0q_dpNE9vYM3N7zHPuKKa__C4PbjoAUE0to2M-mZbAs36zCC3i9joH4jXqmkNwZ-ssKjod2Ow
###
